#!/bin/zsh
set -eu

# Reads one JSON payload from stdin. This sample ignores request fields
# and returns a static plan payload compatible with OpenMac PM Plugin API v1.
cat >/dev/null

cat <<'JSON'
{
  "projectName": "Plugin Demo Project",
  "summary": "Generated by sample PM plugin.",
  "tickets": [
    {
      "title": "Plugin Demo Project · Brainstorm Scope",
      "details": "Acceptance:\nDepends on: none\n- Define 3 product options.\n- Compare risks and delivery cost.\n- Pick one baseline approach.",
      "requiredSkills": ["planning"],
      "storyPoints": 2,
      "epic": "Planning",
      "milestone": "M0 Ideation"
    },
    {
      "title": "Plugin Demo Project · MVP Execution Plan",
      "details": "Acceptance:\nDepends on: Plugin Demo Project · Brainstorm Scope\n- Convert selected option into executable milestones.\n- Define quality gate and release checklist.",
      "requiredSkills": ["planning", "architecture"],
      "storyPoints": 3,
      "epic": "Planning",
      "milestone": "M1 Scope Locked"
    }
  ]
}
JSON
