#!/bin/zsh
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <plugin-id> [target-directory] [plugin-name]" >&2
  exit 1
fi

plugin_id="$1"
target_root="${2:-$PWD}"
plugin_name="${3:-${plugin_id:t}}"

safe_dir_name="${plugin_id:l}"
safe_dir_name="${safe_dir_name//[^a-z0-9._-]/-}"
while [[ "$safe_dir_name" == *"--"* ]]; do
  safe_dir_name="${safe_dir_name//--/-}"
done
safe_dir_name="${safe_dir_name##-}"
safe_dir_name="${safe_dir_name%%-}"
if [[ -z "$safe_dir_name" ]]; then
  safe_dir_name="plugin"
fi

plugin_dir="$target_root/$safe_dir_name"
if [[ -e "$plugin_dir" ]]; then
  echo "Target already exists: $plugin_dir" >&2
  exit 1
fi

mkdir -p "$plugin_dir"

cat > "$plugin_dir/plugin.json" <<JSON
{
  "id": "$plugin_id",
  "name": "$plugin_name",
  "version": "0.1.0",
  "summary": "OpenMac extension scaffold",
  "capabilities": ["pm.plan.generate"],
  "permissions": ["command.execute"],
  "entrypoint": "./run.sh",
  "commands": [
    {
      "id": "health-check",
      "title": "Health Check",
      "subtitle": "Verify extension wiring",
      "slots": ["app.toolbar", "pm.planner.panel"],
      "permissions": ["command.execute"],
      "timeoutSeconds": 30,
      "enabled": true
    },
    {
      "id": "task-note",
      "title": "Task Note",
      "subtitle": "Read selected task context",
      "slots": ["task.card"],
      "permissions": ["command.execute"],
      "timeoutSeconds": 30,
      "enabled": true
    }
  ],
  "uiExtensions": [
    {
      "id": "brainstorm",
      "slot": "pm.planner",
      "title": "Brainstorm Extension",
      "subtitle": "Optional custom PM planner brainstorm card",
      "component": "brainstorm.v1",
      "priority": 10,
      "enabled": true
    }
  ],
  "enabled": true
}
JSON

cat > "$plugin_dir/run.sh" <<'SH2'
#!/bin/zsh
set -euo pipefail

python3 - <<'PY'
import json
import sys

raw = sys.stdin.read().strip() or "{}"
try:
    payload = json.loads(raw)
except Exception:
    payload = {}

if payload.get("type") == "command":
    command_id = payload.get("commandID", "unknown")
    selected_task = payload.get("selectedTask") or {}
    task_title = selected_task.get("title", "")
    message = f"{command_id} executed"
    if task_title:
        message += f" for task '{task_title}'"
    print(json.dumps({"message": message}, ensure_ascii=False))
else:
    project_name = payload.get("projectName", "Sample Project")
    print(json.dumps({
        "projectName": project_name,
        "summary": "Scaffold plan generated by extension template.",
        "tickets": [
            {
                "title": f"{project_name} · Scope",
                "details": "Define goals and acceptance criteria.\\nDepends on: none",
                "requiredSkills": ["planning"],
                "storyPoints": 2,
                "epic": "Planning",
                "milestone": "M1 Scope"
            },
            {
                "title": f"{project_name} · Build",
                "details": "Implement core flow and tests.\\nDepends on: " + f"{project_name} · Scope",
                "requiredSkills": ["swiftui", "testing"],
                "storyPoints": 5,
                "epic": "Core",
                "milestone": "M2 MVP"
            }
        ]
    }, ensure_ascii=False))
PY
SH2
chmod +x "$plugin_dir/run.sh"

cat > "$plugin_dir/README.md" <<'MD'
# OpenMac Extension Scaffold

## Local development

1. Install into OpenMac extension folder from the app Marketplace.
2. Or copy this folder into:

`~/Library/Application Support/OpenMac/Plugins`

3. In OpenMac: `Extensions > Marketplace... > Rescan`

## Contract

- `plugin.json` describes capabilities, commands, UI extension slots.
- `run.sh` receives JSON via stdin and returns JSON via stdout.
- For command contributions, return:

```json
{"message": "..."}
```

- For PM plan generation, return:

```json
{
  "projectName": "...",
  "summary": "...",
  "tickets": []
}
```
MD

echo "Created extension scaffold at: $plugin_dir"
